use MotiAdviser;

INSERT INTO `Class` VALUES 
(NULL,'CH 111 Intro Chem Principles','Chemical concepts for students in health care, biological applications, and environmental studies. Topics include atomic structure, solutions, acids, bases, stoichiometry, equilibrium, biomolecules, and organic functional groups. Lecture, demonstration.',4,Null,Null),
(NULL,'CH 113 Chem of Sustainability','Illustrates how chemistry provides innovative materials, processes, and consumer products that support sustainable solutions related to energy utilization, global warming and pollution prevention.',4,Null,Null),
(NULL,'CH 221 General Chemistry','Chemistry is the study of matter and the changes that it undergoes. It is a science that is central to our understanding of the natural world and it serves as a foundation for all other scientific disciplines. The General Chemistry sequence, beginning with CH 221, is designed for science majors and pre-professional students, and provides an introduction to the experimental and theoretical foundations of chemistry. Students will gain factual knowledge about the terminology and language of chemistry as well as an understanding of the underlying reasons why chemical processes occur. They will be expected to interpret, reason and problem solve using fundamental chemical principles.',4,Null,Null),
(NULL,'CH 222 General Chemistry','Chemistry is the study of matter and the changes that it undergoes. It is a science that is central to our understanding of the natural world and it serves as a foundation for all other scientific disciplines. The second course in the sequence, CH 222, is designed for science majors and pre-professional students, and provides an introduction to the experimental and theoretical foundations of chemistry. Students will gain factual knowledge about the terminology and language of chemistry as well as an understanding of the underlying reasons why chemical processes occur. They will be expected to interpret, reason and problem solve using fundamental chemical principles.',4,Null,Null),
(NULL,'CH 223 General Chemistry','Chemistry is the study of matter and the changes that it undergoes. It is a science that is central to our understanding of the natural world and it serves as a foundation for all other scientific disciplines. This final course in the sequence, CH 223, is designed for science majors and pre-professional students, and provides an introduction to the experimental and theoretical foundations of chemistry. Students will gain factual knowledge about the terminology and language of chemistry as well as an understanding of the underlying reasons why chemical processes occur. They will be expected to interpret, reason and problem solve using fundamental chemical principles.',4,Null,Null),
(NULL,'CH 224H Honors Gen Chemistry','First-year university chemistry for students with excellent backgrounds in high school chemistry, physics, and mathematics. Chemical structure, equilibrium dynamics, thermodynamics, reactions, and an introduction to quantum chemistry. Students cannot receive credit for both CH 221 and CH 224H.',4,Null,Null),
(NULL,'CH 225H Honors Gen Chemistry','First-year university chemistry for students with excellent backgrounds in high school chemistry, physics, and mathematics. Chemical structure, equilibrium dynamics, thermodynamics, reactions, and an introduction to quantum chemistry. Students cannot receive credit for both CH 222 and CH 225H.',4,Null,Null),
(NULL,'CH 226H Honors Gen Chemistry','First-year university chemistry for students with excellent backgrounds in high school chemistry, physics, and mathematics. Chemical structure, equilibrium dynamics, thermodynamics, reactions, and an introduction to quantum chemistry. Students cannot receive credit for both CH 223 and CH 226H.',4,Null,Null),
(NULL,'CIS 105 Explorations Computing','Overview of basic ideas and areas of computer science: includes algorithms, hardware, machine organization, programming languages, networks, artificial intelligence, and associated ethical issues.',4,Null,Null),
(NULL,'CIS 110 Digital Info Process','Introduction to information technology (IT), the study of computer-based information systems. Basics of the Internet and World Wide Web. Students create websites using XHTML and CSS.',4,Null,Null),
(NULL,'CIS 110 Fluency with Info Tech','Introduction to information technology (IT), the study of computer-based information systems. Basics of the Internet and World Wide Web. Students create websites using XHTML and CSS.',4,Null,Null),
(NULL,'CIS 111 Intro Web Programming','Project-based approach to learning computer programming by building interactive web pages using JavaScript and XHTML. Programming concepts including structured and object-oriented program design. CIS 110 recommended.',4,Null,Null),
(NULL,'CIS 111 Web Programming','CIS 111 is an introduction to programming and problem-solving using JavaScript. The course also covers how to script the DOM (Document Object Model) and create dynamic web page effects using JQuery, a JavaScript library.',4,Null,Null),
(NULL,'CIS 115 Multimedia on the Web','Principles and practices of digital imaging, audio, video, and multimedia authoring with Flash for website design. Labs cover multimedia software tools. CIS 110 recommended.',4,Null,Null),
(NULL,'CIS 115 Multimedia Web Program','Intermediate web programming with an emphasis on multimedia (graphics, audio, video). Uses JavaScript, HTML5, and graphics to build interactive web pages.',4,Null,Null),
(NULL,'CIS 122 Intro Prg & Algorithms','Computational problem solving, algorithm design, data structures, and programming using a multi-paradigm programming language. Introduces techniques for program design, testing, and debugging.',4,Null,Null),
(NULL,'CIS 122 Intro Prg & Prob Solv','Computational problem solving, algorithm design, data structures, and programming using a multi-paradigm programming language. Introduces techniques for program design, testing, and debugging.',4,Null,Null),
(NULL,'CIS 170 Science of Computing','This course is an introduction to the field of computer science. It will be oriented to students who are considering a CIS major, but should be of interest to anyone who is curious about what computers are and how they are used in a wide variety of areas that impact our lives today. Some of the topics we will examine are: What is an algorithm? How do computer scientists evaluate the correctness and efficiency of algorithms? What sort of algorithms do scientists use to compare DNA and protein sequences? How are large databases organized? How do scientists access this information over the Internet? Although the topics are fairly technical, the lectures and projects in this course will be accessible to anyone with the basic background in math (the equivalent of Mth 112) Most lab projects will use a programming language named Ruby. Ruby is open source software that can be downloaded and installed on any system. Ruby is included with Mac OS/X 10.4. Instructions for installing it on Windows systems can be found on the class web page.',4,Null,Null),
(NULL,'CIS 199 Sp St Apps with Impact',' ',4,Null,Null),
(NULL,'CIS 199 Sp St Cloud Apps',' ',1,Null,Null),
(NULL,'CIS 199 Sp St Create Droid App','This course focuses on building apps for Android devices (e.g., phones, tablets) using Google\'s App Inventor. Course work will include several assignments intended to teach app development using App Inventor followed by a final project of the student\'s choosing. Android phones will be provided to registered students. The course will be both fun and practical for anyone wishing to learn mobile app development.',4,Null,Null),
(NULL,'CIS 199 Sp St Ethics Info Age','Why can’t I put that on Facebook? I can say whatever I want on the Internet! Questions and comments like these are uttered daily by youth around the U.S. This course will explore the range of ethical questions and social impacts arising from the development and use of new information technologies (e.g., social networks). Discussions regarding questions of privacy, intellectual property, and freedom of speech will be included as we consider several ethical theories that provide students with basic methods for addressing these questions.',3,Null,Null),
(NULL,'CIS 199 Sp St Intro to Apps',' ',4,Null,Null),
(NULL,'CIS 199 Sp St Make Break Codes',' ',3,Null,Null),
(NULL,'CIS 199 Sp St Make/Break Codes',' ',3,Null,Null),
(NULL,'CIS 199 Sp St Managing Soc Med',' ',1,Null,Null),
(NULL,'CIS 199 Sp St Softw Carpentry',' ',1,Null,Null),
(NULL,'CIS 210 Computer Science I','CIS 210 is the first course in the Computer and Information Science major sequence. The primary objective of this course is to introduce the basic concepts and practices of computer science. The core ideas of computer programming will be explored using the Python programming language. We will cover fundamental approaches to problem solving and the creation of software solutions as well as introduce the notions of data abstraction and object-oriented programming.',4,Null,Null),
(NULL,'CIS 211 Computer Science II','This course continues instruction in object-oriented design and programming. Class hierarchies, inheritance, abstract classes, and interfaces are used to represent the structure of a problem domain and allow reuse and specialization of methods and instance variables by subclasses. Several important \'patterns,\' i.e., ways of using the language, are introduced to facilitate problem solving in an object-oriented context. A significant programming project is developed over a series of lab assignments.',4,Null,Null),
(NULL,'CIS 212 Computer Science III','The course introduces the concept of abstract data type, and several abstract data types, e.g., lists, stacks, queues, binary trees, are defined and implemented. The course also covers basics of algorithm design and analysis. Recursive and iterative approaches to problem solving are covered, with means for developing and analyzing the resultant algorithms. Notions of correctness proof and Big-O time complexity are explored.',4,Null,Null),
(NULL,'CIS 313 Interm Data Structures','Design and analysis of data structures as means of engineering efficient software; attention to data abstraction and encapsulation. Lists, trees, heaps, stacks, queues, dictionaries, priority queues.',4,Null,Null),
(NULL,'CIS 314 Computer Organization','Introduction to computer organization and instruction-set architecture--digital logic design, binary arithmetic, design of central processing unit and memory, machine-level programming.',4,Null,Null),
(NULL,'CIS 315 Intermed Algorithms','Algorithm design, worst-case and average-behavior analysis, correctness, computational complexity.',4,Null,Null),
(NULL,'CIS 323 Data Struc Lab','Programming laboratory. Data structures and object-oriented implementation.',2,Null,Null),
(NULL,'CIS 330 C/C++ and Unix','Practical software design and programming activities in a C/C++ and Unix environment, with emphasis on the details of C/C++ and good programming style and practices.',4,Null,Null),
(NULL,'CIS 399 Sp St iPhone/iPad Apps','Each student will gain an understanding of the iOS development platform and develop an iOS-based application.',4,Null,Null),
(NULL,'CIS 399 Sp St Mob App Dev/Andr',' ',4,Null,Null),
(NULL,'CIS 399 Sp St Programming Chig',' ',2,Null,Null),
(NULL,'CIS 399 Sp St Unix System Admn',' ',4,Null,Null),
(NULL,'CIS 399 Sp St Web Engineering',' ',4,Null,Null),
(NULL,'CIS 401 Research',' ',2,Null,Null),
(NULL,'CIS 403 Thesis',' ',2,Null,Null),
(NULL,'CIS 404 Internship',' ',2,Null,Null),
(NULL,'CIS 405 Reading',' ',2,Null,Null),
(NULL,'CIS 406 Field Studies',' ',2,Null,Null),
(NULL,'CIS 407 Sem Career/Internships','Opportunity to study in greater depth specific topics arising out of other courses.',2,Null,Null),
(NULL,'CIS 407 Sem Game Theory','Opportunity to study in greater depth specific topics arising out of other courses.',2,Null,Null),
(NULL,'CIS 407 Sem Mobile Apps','Opportunity to study in greater depth specific topics arising out of other courses.',2,Null,Null),
(NULL,'CIS 407 Sem Online Softwr Eng','Opportunity to study in greater depth specific topics arising out of other courses.',2,Null,Null),
(NULL,'CIS 407 Sem Prog Competition','Opportunity to study in greater depth specific topics arising out of other courses.',2,Null,Null),
(NULL,'CIS 407 Sem Research Colloq','Opportunity to study in greater depth specific topics arising out of other courses.',1,Null,Null),
(NULL,'CIS 407 Sem Robotics','Opportunity to study in greater depth specific topics arising out of other courses.',2,Null,Null),
(NULL,'CIS 407 Sem Scientific Res','Opportunity to study in greater depth specific topics arising out of other courses.',2,Null,Null),
(NULL,'CIS 407 Sem Secure Development','Opportunity to study in greater depth specific topics arising out of other courses.',2,Null,Null),
(NULL,'CIS 407 Sem Soft Tools Science','This course provides a practical overview of research programming and tools, including use of the University of Oregon’s local high-performance computing cluster, ACISS. The class is intended for researchers in any science field looking to gain technical proficiency with scientific programming and tools. Students are encouraged to use their own research problems to direct their learning. At the end of the class, students will have been introduced to technical skills useful in scientific research including the usage of the Unix command-line, basic python scripting, and the ability to submit jobs to the ACISS cluster.',2,Null,Null),
(NULL,'CIS 407 Sem Women in Tech','Opportunity to study in greater depth specific topics arising out of other courses.',1,Null,Null),
(NULL,'CIS 409 Prac Supv Consulting','The student assists other students who are enrolled in introductory programming classes. For each four hours of scheduled weekly consulting, the student is awarded 1 credit. R for maximum of 4 credits.',2,Null,Null),
(NULL,'CIS 410 Adv Funcational Prog','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Adv Systems Security','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Cryptography','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Global Dist S/W Dev','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Graphic Prog in Python','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Machine Learning','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Mobile Netwrk/Security','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Online Social Network','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Parallel Computing','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Peer Advising','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',2,Null,Null),
(NULL,'CIS 410 Probabilistic Methods','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Prog Analysis & Trans','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Sched Distrib Systems','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Secure Development','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 410 Visualization','New courses are offered under this number, the first year or two, before final definition of the courses and permanent approval by the University Senate and Oregon University System.',4,Null,Null),
(NULL,'CIS 413 Adv Data Structures','Complex structures, storage management, sorting and searching, hashing, storage of texts, and information compression.',4,Null,Null),
(NULL,'CIS 415 Operating Systems','Principles of operating system design. Process and memory management, concurrency, scheduling, input-output and file systems, security.',4,Null,Null),
(NULL,'CIS 420 Automata Theory','Provides a mathematical basis for computability and complexity. Models of computation, formal languages, Turing machines, solvability. Nondeterminism and complexity classes.',4,Null,Null),
(NULL,'CIS 422 Software Method I','Technical and nontechnical aspects of software development, including specification, planning, design, development, management and maintenance of software projects. Student teams complete projects.',4,Null,Null),
(NULL,'CIS 423 Software Method II','Application of concepts and methodologies covered in CIS 422/522. Student teams complete a large system design and programming project. Final system specification, test plan, user documentation, and system walk throughs.',4,Null,Null),
(NULL,'CIS 425 Princ of Program Lang','Syntax and semantics. Scope rules, environments, stores, denoted and expressed values, procedures, and parameters. Definitional interpreters. Types, overloading, parametric polymorphism, and inheritance. Varieties of abstraction.',4,Null,Null),
(NULL,'CIS 427 Intro to Logic','Basic notions of logic: propositional logic, first-order logic, Hilbert systems, sequent calculus, natural deduction. Soundness, completeness, undecidability. Current research in logic frameworks, automated deduction, Curry-Howard isomorphism.',4,Null,Null),
(NULL,'CIS 429 Computer Architecture','RISC (reduced instruction-set computer) and CISC (complex instruction-set computer) design, storage hierarchies, high-performance processor design, pipelining, vector processing, networks, performance analysis.',4,Null,Null),
(NULL,'CIS 432 Intro to Networks','Principles of computer network design. Link technologies, packet switching, routing, inter-networking, reliability. Internet protocols. Programming assignments focus on protocol design.',4,Null,Null),
(NULL,'CIS 433 Comp & Netwrk Security','Security for various aspects of computers and networks. Elementary cryptography, program security, trusted operating systems, network security, privacy, and legal and ethical issues.',4,Null,Null),
(NULL,'CIS 441 Intro Comput Graphics','Introduction to the hardware, geometrical transforms, interaction techniques, and shape representation schemes that are important in interactive computer graphics. Programming assignments using contemporary graphics hardware and software systems.',4,Null,Null),
(NULL,'CIS 443 User Interfaces','Introduction to user interface software engineering. Emphasis on theory of interface design, understanding the behavior of the user, and implementing programs on advanced systems.',4,Null,Null),
(NULL,'CIS 445 Modeling & Simulation','Theoretical foundations and practical problems for the modeling and computer simulation of discrete and continuous systems. Simulation languages, empirical validation, applications in computer science.',4,Null,Null),
(NULL,'CIS 451 Data-Base Processing','Fundamental concepts of DBMS. Data modeling, relational models and normal forms. File organization and index structures. SQL, embedded SQL, and concurrency control.',4,Null,Null),
(NULL,'CIS 452 Database Issues','Covers central database issues such as access methods, security, tuning, and concurrency control. Examines alternative database models.',4,Null,Null),
(NULL,'CIS 453 Data Mining','Databases, machine learning, artificial intelligence, statistics, and data visualization. Examines data warehouses, data preprocessing, association and classification rule mining, and cluster analysis.',4,Null,Null),
(NULL,'CIS 454 Bioinformatics','Introduction to bioinformatics from a computer science perspective covering algorithms for basic operations such as sequence comparison and phylogenetic inference on existing databases.',4,Null,Null),
(NULL,'CIS 455 Computational Science','Solving scientific problems with high-performance computers; algorithms, languages, and software used in scientific computing and visualization. Group projects on current research in physics, chemistry, biology, and other sciences.',4,Null,Null),
(NULL,'CIS 461 Intro to Compilers','Lexical analysis, parsing, attribution, code generation.',4,Null,Null),
(NULL,'CIS 471 Intro Artificial Intel','Basic themes, issues, and techniques of artificial intelligence, including agent architecture, knowledge representation and reasoning, problem solving and planning, game playing, and learning.',4,Null,Null),
(NULL,'CIS 472 Machine Learning','A broad introduction to machine learning and its established algorithms. Topics include concept learning, decision trees, neural network.',4,Null,Null),
(NULL,'CIS 490 Computer Ethics','Addresses ethical issues and social impacts of computing. Topics include crime, hacking, intellectual property, privacy, software reliability, employment, and worldwide networks.',4,Null,Null),
(NULL,'MATH 111 College Algebra','Algebra needed for calculus including graph sketching, algebra of functions, polynomial functions, rational functions, exponential and logarithmic functions, linear and nonlinear functions.',4,Null,Null),
(NULL,'MATH 112 Elementary Functions','Exponential, logarithmic, and trigonometric functions. Intended as preparation for MATH 251.',4,Null,Null),
(NULL,'MATH 231 Elem Discrete Math I','Sets, mathematical logic, induction, sequences, and functions. Sequence.',4,Null,Null),
(NULL,'MATH 232 Elem Discrete Math II','Relations, theory of graphs and trees with applications, permutations and combinations.',4,Null,Null),
(NULL,'MATH 233 Elem Discrete Math III','Discrete probability, Boolean algebra, elementary theory of groups and rings with applications.',4,Null,Null),
(NULL,'MATH 246 Calc for Biol Sci I','For students in biological science and related fields. Emphasizes modeling and applications to biology. Differential calculus and applications. Sequence. Students cannot receive credit for more than one of MATH 241, 246, 251.',4,Null,Null),
(NULL,'MATH 247 Calc for Biol Sci II','MATH 247 discusses techniques and applications of integral calculus, along with an introduction to single and coupled differential equations. Topics include integration rules for polynomial, exponential, logarithmic, and trigonometric functions and the substitution and parts techniques of integration. The differential equations content focuses on mathematical modeling and determining stability of equilibria in autonomous individual and coupled differential equations. Solutions for separable and certain autonomous differential equations are discussed.',4,Null,Null),
(NULL,'MATH 251 Calculus I','Single variable differential calculus. The course includes both theoretical and applied results for limits and derivatives of elementary functions-- i.e., polynomial, rational, trigonometric, exponential, and logarithmic functions. Implicit differentiation and the connections of derivatives with graphs is discussed.',4,Null,Null),
(NULL,'MATH 252 Calculus II','Single variable integration and the fundamental theorem of Calculus. The emphasis is on the computation of areas, volumes, and integration of elementary (i.e., polynomial, rational, trigonometric, exponential, and logarithmic) functions. Applications of calculus to physical situations are discussed. Prerequisites: MATH 251.',4,Null,Null),
(NULL,'MATH 253 Calculus III','The course incorporates such concepts of Calculus as infinite sequences and series, improper integrals, and power series. Prerequisites: MATH 251 and MATH 252. A good understanding of differentiation and integration is assumed.',4,Null,Null),
(NULL,'MATH 256 Intro Differ Equations','Introduction to differential equations and applications. Linear algebra is introduced as needed.',4,Null,Null),
(NULL,'MATH 261 Calculus with Theory I','The course, which is the first of three in the sequence, introduces students to differential calculus from the theoretical point of view, how calculus works as well as how to use it. Topics include axiomatic treatment of real numbers, limits, continuity, and derivatives. An ability to read, understand and write proofs will be stressed. A precise knowledge of concepts and definitions is essential.',4,Null,Null),
(NULL,'MATH 262 Calculus with Theo II','The course, which is the second of three in the sequence, introduces students to differential calculus from the theoretical point of view, how calculus works as well as how to use it. Topics include derivatives, integrals, fundamental theorem of calculus, and rigorous study of trigonometric, logarithmic, and exponential functions. An ability to read, understand and write proofs will be stressed. A precise knowledge of concepts and definitions is essential.',4,Null,Null),
(NULL,'MATH 263 Calculus with Theo III','The course, which is the last of three in the sequence, introduces students to differential calculus from the theoretical point of view, how calculus works as well as how to use it. Topics include infinite sequences, infinite series, Taylor\'s theorem, uniform convergence, power series, and complex functions. An ability to read, understand and write proofs will be stressed. A precise knowledge of concepts and definitions is essential.',4,Null,Null),
(NULL,'MATH 281 Several-Variab Calc I','ntroduction to calculus of functions of several variables including partial differentiation; gradient, divergence, and curl; line and surface integrals; Green\'s and Stokes\'s theorems. Linear algebra introduced as needed. Sequence.',4,Null,Null),
(NULL,'MATH 282 Several-Variab Calc II','Introduction to calculus of functions of several variables including partial differentiation; gradient, divergence, and curl; line and surface integrals; Green\'s and Stokes\'s theorems. Linear algebra introduced as needed.',4,Null,Null),
(NULL,'MATH 307 Introduction to Proof','Proof is how mathematics establishes truth and communicates ideas. Introduces students to proof in the context of interesting mathematical problems.',4,Null,Null),
(NULL,'MATH 315 Elementary Analysis','Rigorous treatment of certain topics introduced in calculus including continuity, differentiation and integration, power series, sequences and series, uniform convergence and continuity.',4,Null,Null),
(NULL,'MATH 341 Elem Linear Algebra','Vector and matrix algebra; n-dimensional vector spaces; systems of linear equations; linear independence and dimension; linear transformations; rank and nullity; determinants; eigenvalues; inner product spaces; theory of a single linear transformation. Sequence.',4,Null,Null),
(NULL,'MATH 342 Elem Linear Algebra','Vector and matrix algebra; n-dimensional vector spaces; systems of linear equations; linear independence and dimension; linear transformations; rank and nullity; determinants; eigenvalues; inner product spaces; theory of a single linear transformation.',4,Null,Null),
(NULL,'MATH 343 Statistic Models & Mth','Review of theory and applications of mathematical statistics including estimation and hypothesis testing.',4,Null,Null),
(NULL,'MATH 346 Number Theory','Topics include congruences, Chinese remainder theorem, Gaussian reciprocity, basic properties of prime numbers.',4,Null,Null),
(NULL,'MATH 351 Elem Numeric Analy I','Basic techniques of numerical analysis and their use on computers. Topics include root approximation, linear systems, interpolation, integration, and differential equations. Sequence. Not offered 2005-6.',4,Null,Null),
(NULL,'MATH 391 Fund Abstract Alg I','Introduction to algebraic structures including groups, rings, fields, and polynomial rings. Sequence.',4,Null,Null),
(NULL,'MATH 392 Fund Abstract Alg II','Introduction to algebraic structures including groups, rings, fields, and polynomial rings.',4,Null,Null),
(NULL,'MATH 393 Fund Abstract Alg III','Introduction to algebraic structures including groups, rings, fields, and polynomial rings.',4,Null,Null),
(NULL,'MATH 411 Func Complex Var I','Complex numbers, linear fractional transformations, Cauchy-Riemann equations, Cauchy\'s theorem and applications, power series, residue theorem, harmonic functions, contour integration, conformal mapping, infinite products. Sequence.',4,Null,Null),
(NULL,'MATH 412 Func Complex Var II','Complex numbers, linear fractional transformations, Cauchy-Riemann equations, Cauchy\'s theorem and applications, power series, residue theorem, harmonic functions, contour integration, conformal mapping, infinite products.',4,Null,Null),
(NULL,'MATH 413 Intro Analysis I','Differentiation and integration on the real line and in a dimensional Euclidean space; normed linear spaces and metric spaces; vector field theory and differential forms. Sequence.',4,Null,Null),
(NULL,'MATH 414 Intro Analysis II','Differentiation and integration on the real line and in a dimensional Euclidean space; normed linear spaces and metric spaces; vector field theory and differential forms.',4,Null,Null),
(NULL,'MATH 415 Intro Analysis III','Differentiation and integration on the real line and in a dimensional Euclidean space; normed linear spaces and metric spaces; vector field theory and differential forms. Sequence.',4,Null,Null),
(NULL,'MATH 420 Ord Differential Equat','Ordinary differential equations. General and initial value problems. Explicit, numerical, graphical solutions; phase portraits. Existence, uniqueness, stability. Power series methods. Gradient flow; periodic solutions.',4,Null,Null),
(NULL,'MATH 421 Fourier Analysis I','Introduction to PDEs; wave and heat equations. Classical Fourier series on the circle; applications of Fourier series. Generalized Fourier series, Bessel and Legendre series.',4,Null,Null),
(NULL,'MATH 422 Fourier Analysis II','General theory of PDEs; the Fourier transform. Laplace and Poisson equations; Green\'s functions and application. Mean value theorem and max-min principle.',4,Null,Null),
(NULL,'MATH 425 Statistical Methods I','Statistical methods for upper-division and graduate students anticipating research in nonmathematical disciplines. Presentation of data, sampling distributions, tests of significance, confidence intervals, linear regression, analysis of variance, correlation, statistical software. Sequence. Only nonmajors may receive upper-division credit. Students cannot receive credit for both MATH 243 and 425.',4,Null,Null),
(NULL,'MATH 431 Intro to Topology','Elementary point-set topology with an introduction to combinatorial topology and homotopy. Sequence.',4,Null,Null),
(NULL,'MATH 432 Intro to Topology','Elementary point-set topology with an introduction to combinatorial topology and homotopy. Sequence.',4,Null,Null),
(NULL,'MATH 433 Intro Differen Geom','Plane and space curves, Frenet-Serret formula surfaces. Local differential geometry, Gauss-Bonnet formula, introduction to manifolds.',4,Null,Null),
(NULL,'MATH 441 Linear Algebra','Theory of vector spaces over arbitrary fields, theory of a single linear transformation, minimal polynomials, Jordan and rational canonical forms, quadratic forms, quotient spaces.',4,Null,Null),
(NULL,'MATH 444 Intro Abstract Alg I','Theory of groups, rings, and fields. Polynomial rings, unique factorization, and Galois theory. Sequence.',4,Null,Null),
(NULL,'MATH 445 Intro Abstract Alg II','Theory of groups, rings, and fields. Polynomial rings, unique factorization, and Galois theory.',4,Null,Null),
(NULL,'MATH 446 Intro Abtract Alg III','Theory of groups, rings, and fields. Polynomial rings, unique factorization, and Galois theory.',4,Null,Null),
(NULL,'MATH 456 Networks & Combinator','Fundamentals of modern combinatorics; graph theory; networks; trees; enumeration, generating functions, recursion, inclusion and exclusion; ordered sets, lattices, Boolean algebras.',4,Null,Null),
(NULL,'MATH 457 Discrete Dynam Systems','Linear and nonlinear first-order dynamical systems; equilibrium, cobwebs, Newton\'s method. Bifurcation and chaos. Introduction to higher-order systems. Applications to economics, genetics, ecology.',4,Null,Null),
(NULL,'MATH 461 intro Methods Stats I','Discrete and continuous probability models; useful distributions; applications of moment-generating functions; sample theory with applications to tests of hypotheses, point and confidence interval estimates. Sequence.',4,Null,Null),
(NULL,'MATH 462 Intro Methods Stats II','Discrete and continuous probability models; useful distributions; applications of moment-generating functions; sample theory with applications to tests of hypotheses, point and confidence interval estimates.',4,Null,Null),
(NULL,'MATH 463 Regressions & Variance','Multinomial distribution and chi-square tests of fit, simple and multiple linear regression, analysis of variance and covariance, methods of model selection and evaluation, use of statistical software.',4,Null,Null),
(NULL,'PHYS 201 General Physics','PHYS 201 introduces the physics of classical dynamics. Based on Newton\'s three laws of mechanics, the variables required to describe motion - displacement, velocity and acceleration - are related to the variables that quantify the cause of motion force and momentum. The relationship between energy and motion is also presented. Static objects, motion under gravity and circular motion are all considered. The dynamics of fluids (gases and liquids) are also presented.',4,Null,Null),
(NULL,'PHYS 202 General Physics','PHYS 202 introduces wave motion through the concepts of harmonic motion, vibrations and resonance. The physics and applications of sounds waves are followed by heat transfer and the laws of thermodynamics. Practical systems such as heat engines, refrigerators and air conditioners are explained. Finally the basic properties of light waves are presented along with optical instruments that make use of these properties, including microscopes, telescopes and cameras.',4,Null,Null),
(NULL,'PHYS 203 General Physics','PHYS 203 describes electricity, magnetism and their unification using Maxwell\'s equations, leading to the description of light waves as electromagnetic radiation. Finally, the principles of modern physics are developed, including quantum physics and special relativity, and technology based on modern physics concepts are explained.',4,Null,Null),
(NULL,'PHYS 251 Foundat Physics','The main topic of Phys 251 is Newton\'s theory of motion and its applications. The first few weeks cover units and dimension, one and two-dimensional kinematics, derivatives, and vectors. The next few weeks introduce Newton\'s theory of motion and techniques for applying these concepts to predict the outcomes of simplified problems in mechanics, such as determining the motion of objects subject to constant forces. The next topic is Newton\'s theory of gravitation, including an introduction to planetary motion. This is followed by the formulation and application of the great conservation principles of classical physics: energy and momentum. Rotational dynamics, including torque and angular momentum is the next subject. The last topic of the term is the application of these principles to the special case of mechanical equilibrium, the stability conditions for structures, and the strength of materials.',4,Null,Null),
(NULL,'PHYS 252 Foundat Physics','The second term of the sequence focuses primarily on the physics of oscillations and waves, with specific applications to mechanics, sound, and optics. Other topics include fluids and strength of materials.',4,Null,Null),
(NULL,'PHYS 253 Foundat Physics I','This term is devoted to the subject of electricity and magnetism. We start with electrostatics: Coulomb\'s force, the electric field and methods for its calculation, Gauss\'s law, the electric potential, electric dipoles, capacitance, dielectrics, and electrical conductivity.',4,Null,Null),
(NULL,'BI 211 Gen Biol I: Cells','In this first course of the general biology sequence we study the biological processes from a cellular prospective. These concepts are central to understanding all other areas of biology. BI 211 is a prerequisite for all the other general biology courses in the sequence (Bi212-214).',4,Null,Null),
(NULL,'BI 212 Gen Biol II: Organisms','BI 212 is about the development and physiology of plants and animals. The course focuses on those aspects of physiology that seem to be universal across the enormous range of organisms that have evolved on our planet. We cover the topics of temperature regulation and the constraints imposed by temperature on organism level adaptations, mechanisms of short and long range transport in plants and animals and the constraints that geometry and the nature of diffusion impose on body plans, plant and animal nutrition (including the biology of appetite and the remarkable complexity of soil). We study the five senses and optical illusions by way of the nervous system, and the mechanisms by which plants seem to act as though they had a brain as they respond to various features of light. We cover the topic of development, by which single celled zygotes become complex and diverse organisms with a special emphasis on the genetics of development. Throughout we investigate the roles of natural selection on the physiological features of plants and animals. The course is part of a sequence, so the prerequisite is BI 211.',4,Null,Null),
(NULL,'BI 213 Gen Biol III: Populat','In this third term of the general biology sequence we build on concepts of how cells and organisms function to study processes and patterns that occur between different organisms and with organisms and their environments. We begin by examining mechanisms that cause genetic change in populations over time with a special focus on natural selection. We then examine the species concept and look at patterns of evolutionary change over long time periods. The last half of the term looks at ecological theory where we study different models of population growth and factors that regulate population growth in various organisms, including humans. We study ways in which two or more species interact and apply these ideas to current issues such as invasive species and loss of biodiversity. At the end of the term we study ecosystem processes such as energy flow and nutrient cycling between various ecosystem components. These are done using a case study such as tall grass prairie ecosystems, fire, and bison grazing.',4,Null,Null),
(NULL,'PSY 201 Mind and Brain','The primary goal of this course is to introduce students to basic concepts about core mental functions such as learning, memory and attention, and how the brain enables these functions. Across a variety of domains, this course examines the core principles that govern how our mind functions, as well as how these principles arise from the underlying neural substrate.',4,Null,Null),
(NULL,'PSY 202 Mind and Society','The course takes a research-based approach to psychology, considering at every step along the way how psychologists can best empirically test their theories and add new knowledge about human behavior. Students are given a chance to hone their own observation skills, to develop and test hypotheses, and to become critical consumers of research findings.',4,Null,Null),
(NULL,'PSY 304 Biopsychology','Relationships between brain and endocrine activity and behavior. Topics include sensation, perception, sexual behavior, drug effects, eating, drinking, sleeping, dreaming, and learning.',4,Null,Null),
(NULL,'PSY 330 Thinking','Psychological methods involved in problem solving, complex learning, and various forms of rational and irrational reasoning and belief systems.',4,Null,Null),
(NULL,'PSY 348 Music and the Brain','Explores the neural correlates of our perception of tonality, harmony, melody, and rhythm and how these relate to neurobiology, brain damage, and cognitive neuroscience.',4,Null,Null),
(NULL,'GEOG 141 Natural Environment','The earth\'s physical landscapes, vegetation patterns, weather, and climate; emphasis on the dynamic interactions among climate, landforms, vegetation, and soils. Gavin, Marcus.',4,Null,Null),
(NULL,'GEOG 321 Climatology','Energy and moisture in the atmosphere, atmospheric circulation, controls of regional and microclimates, applied climatology, climatic variations, past and future climates. Bartlein.',4,Null,Null),
(NULL,'GEOG 322 Geomorphology','Geomorphology is the study of landforms on the surface of Earth and other planets, and the processes that form them. Geomorphology is a subfield of both physical geography and geology. Physical geography provides an integrated understanding of the systems that create our natural environment, including geomorphology, climatology, biogeography, and hydrology, and this course is part of the core physical geography sequence (Geog 321, 322, 323).',4,Null,Null),
(NULL,'GEOG 323 Biogeography','The Earth supports an incredible diversity of life. Biogeography is the study of the spatial patterns of this diversity both in the present and in the past. Biogeographers synthesize information from a very broad range of fields, including ecology, evolution, paleontology, and climatology. But biogeography is also a vigorous modern science concerned with developing and testing biogeographic theory. This course will provide the ecological and historical foundations for understanding the distribution and abundance of species, and the changes in distribution and abundance of species over time. Concepts presented in this class are highly relevant to conservation issues related to human impacts on ecosystems and increasingly rapid climate change.',4,Null,Null),
(NULL,'GEOL 201 Earth\'s Interior Heat','This introduction to physical geology emphasizes plate tectonics as the unifying concept for understanding the processes that cause earthquakes, volcanism and mountain building on the Earth. The Earth is a dynamic planet, and over its long history mountain belts have risen and been eroded away, continents have shifted their positions, new ocean basins have formed and sometimes closed up again, and volcanic activity has reshaped the continents and sea floor. The course begins with the evidence that supports the theory of plate tectonics and a discussion of how the interior and surface of the Earth interact with the oceans and atmosphere. Topics covered in the course include minerals, the formation of igneous and metamorphic rocks, volcanic activity, how rocks are deformed as mountains grow, why earthquakes occur, the composition and structure of the earth\'s interior, and the ways by which geologic time can be measured.',4,Null,Null),
(NULL,'GEOL 202 Surface & Envir Geol','Earth materials, the rock record, human interactions with surface environment. Sedimentary rocks and environments, chemical and physical weathering, mineral and energy resources, hydrogeology, ground-water contamination, surface processes, human impacts. Weekly lectures, two-hour laboratory.',4,Null,Null),
(NULL,'GEOL 203 Evolution of the Earth','Topics presented in this course include: evolution of the crust and atmosphere; geologic time; evolutionary mechanisms; principles of stratigraphy; record of earliest organisms; processes of fossilization; appearance of multicellular organisms; paleogeography of continents; mountain building and erosion; Paleozoic stratigraphy and organisms; formation and breakup of Pangaea; Mesozoic and Cenozoic climates, stratigraphy, plants and animals, especially evolution of the dinosaurs, pterosaurs, and mammals; major extinctions and possible causes; the Pleistocene ice age and its causes; evolution of hominids.',4,Null,Null),
(NULL,'WR 320 Scientific & Techn Wr','Emphasis on form, function, and style of scientific, professional, and technical writing; weekly writing assignments include proposals, reports, definitions, instructions, summaries. Use of documentation in publication.',4,Null,Null),
(NULL,'WR 321 Business Communication','Practice in writing and analyzing internal and external messages common to business, industry, and professions. Suggested for business and management students. McBride.',4,Null,Null),
(NULL,'WR 121 College Composition I','Written reasoning as discovery and inquiry. Frequent essays explore relationship of thesis to structure and audience. Strong focus on the process of revising. Regular work on editing.',4,Null,Null),
(NULL,'WR 122 College Composition I','Written reasoning as a process of argument. Developing and supporting theses in response to complex questions. Attention to critical reading in academic setting. Continuing focus on revising and editing.',4,Null,Null),
(NULL,'WR 123 College Composition III','Written reasoning in the context of research. Practice in writing documented essays based on the use of sources. Continuing focus on revising and editing.',4,Null,Null);






INSERT INTO `DependentClass` VALUES 
(3,95,'N'),
(4,3,'Y'),
(4,6,'Y'),
(5,4,'Y'),
(5,7,'Y'),
(6,100,'Y'),
(6,102,'Y'),
(6,106,'Y'),
(7,6,'Y'),
(7,3,'N'),
(8,7,'N'),
(8,4,'N'),
(29,28,'N'),
(30,29,'N'),
(31,30,'N'),
(32,30,'N'),
(33,31,'N'),
(34,30,'N'),
(35,32,'N'),
(58,31,'N'),
(59,31,'N'),
(60,31,'N'),
(61,31,'N'),
(62,31,'N'),
(63,31,'N'),
(64,31,'N'),
(65,31,'N'),
(66,31,'N'),
(67,31,'N'),
(68,31,'N'),
(69,31,'N'),
(70,31,'N'),
(71,31,'N'),
(72,31,'N'),
(73,31,'N'),
(74,35,'Y'),
(74,33,'Y'),
(75,33,'N'),
(76,31,'N'),
(77,76,'N'),
(78,33,'N'),
(79,78,'N'),
(80,35,'Y'),
(80,34,'Y'),
(81,35,'Y'),
(81,34,'Y'),
(82,74,'N'),
(83,35,'Y'),
(83,34,'Y'),
(84,31,'N'),
(85,35,'N'),
(85,33,'N'),
(86,31,'N'),
(86,32,'N'),
(87,86,'N'),
(88,86,'N'),
(92,33,'N'),
(93,33,'N'),
(94,30,'N'),
(96,95,'N'),
(97,96,'N'),
(98,97,'N'),
(99,98,'N'),
(100,96,'N'),
(101,100,'N'),
(102,96,'N'),
(103,102,'N'),
(104,103,'N'),
(105,104,'N'),
(107,106,'N'),
(108,107,'N'),
(109,104,'N'),
(110,109,'N'),
(111,103,'Y'),
(111,107,'Y'),
(111,101,'Y'),
(112,104,'N'),
(113,103,'N'),
(114,113,'N'),
(115,103,'N'),
(116,104,'N'),
(117,104,'N'),
(118,113,'N'),
(119,118,'N'),
(120,119,'N'),
(121,109,'N'),
(122,111,'N'),
(123,109,'N'),
(123,112,'N'),
(124,123,'N'),
(125,124,'Y'),
(126,108,'Y'),
(126,112,'Y'),
(127,109,'N'),
(127,105,'N'),
(128,127,'N'),
(129,95,'N'),
(130,112,'N'),
(131,130,'N'),
(132,110,'Y'),
(132,114,'Y'),
(133,114,'N'),
(134,114,'N'),
(135,134,'N'),
(136,135,'N'),
(137,116,'Y'),
(137,97,'Y'),
(138,137,'N'),
(139,104,'N'),
(139,108,'N'),
(140,139,'Y'),
(141,140,'Y'),
(142,96,'N'),
(143,142,'N'),
(144,143,'N'),
(145,102,'N'),
(145,96,'N'),
(146,145,'Y'),
(147,146,'Y'),
(148,1,'Y'),
(148,2,'Y'),
(148,3,'Y'),
(148,6,'Y'),
(149,148,'N'),
(150,149,'N'),
(157,156,'N'),
(158,156,'N'),
(159,156,'N'),
(161,160,'N'),
(162,160,'N'),
(166,165,'N'),
(167,165,'N'),
(163,166,'Y'),
(163,167,'Y'),
(164,166,'Y'),
(164,167,'Y');


INSERT INTO `Major` VALUES 
(Null,'CIS','Business Information Systems'),
(Null,'CIS','Computational Science'),
(Null,'CIS','Computer Networks'),
(Null,'CIS','Computer Security'),
(Null,'CIS','Database and Informatics'),
(Null,'CIS','Foundations'),
(Null,'CIS','Software Development');






INSERT INTO `RequireType` VALUES 
(Null,'Lower-Division Core Courses',20),
(Null,'Upper-Division Core Courses',28),
(Null,'Mathematics Requirements 1',8),
(Null,'Mathematics Requirements 2',8),
(Null,'Science Requirements',12),
(Null,'Colleage Writing',8),
(Null,'Writing Core Course',4),
(Null,'Upper-Division Math Elective',4),
(Null,'BIS Upper-Division CIS Elective',8),
(Null,'BIS Track Requirements',12),
(Null,'CSC Track Requirements 1',4),
(Null,'CSC Track Requirements 2',8),
(Null,'CN Track Requirements',12),
(Null,'CSE Track Requirements',12),
(Null,'DI Track Requirements 1',8),
(Null,'DI Track Requirements 2',4),
(Null,'FUN Track Requirements',20),
(Null,'SD Track Requirements',12),
(Null,'CSC Upper-Division CIS Elective',8),
(Null,'CN Upper-Division CIS Elective',8),
(Null,'CSE Upper-Division CIS Elective',8),
(Null,'DI Upper-Division CIS Elective',8),
(Null,'SD Upper-Division CIS Elective',8);




INSERT INTO `GraduateRule` VALUES 
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(1,7),
(1,8),
(1,9),
(1,10),
(2,1),
(2,2),
(2,3),
(2,4),
(2,5),
(2,6),
(2,7),
(2,8),
(2,19),
(2,11),
(2,12),
(3,1),
(3,2),
(3,3),
(3,4),
(3,5),
(3,6),
(3,7),
(3,8),
(3,20),
(3,13),
(4,1),
(4,2),
(4,3),
(4,4),
(4,5),
(4,6),
(4,7),
(4,8),
(4,21),
(4,14),
(5,1),
(5,2),
(5,3),
(5,4),
(5,5),
(5,6),
(5,7),
(5,8),
(5,22),
(5,15),
(5,16),
(6,1),
(6,2),
(6,3),
(6,4),
(6,5),
(6,6),
(6,7),
(6,8),
(6,17),
(7,1),
(7,2),
(7,3),
(7,4),
(7,5),
(7,6),
(7,7),
(7,8),
(7,23),
(7,18);




















INSERT INTO `GroupsOfType` VALUES 
(Null,1,'N','Y'), /*Lower-Division Core Courses; 1 group*/
(Null,2,'N','Y'), /*Upper-Division Core Courses; 1 group*/
(Null,3,'Y','Y'), /*Mathematics Requirements 1; 3 groups*/
(Null,3,'Y','Y'),
(Null,3,'Y','Y'),
(Null,4,'N','Y'),/*Mathematics Requirements 2; 1 group*/
(Null,5,'Y','N'),/*Science Requirements; 8 groups*/
(Null,5,'Y','N'),
(Null,5,'Y','N'),
(Null,5,'Y','N'),
(Null,5,'Y','N'),
(Null,5,'Y','N'),
(Null,5,'Y','N'),
(Null,5,'Y','N'),
(Null,5,'Y','N'),
(Null,6,'N','N'),/*Colleage Writing; 1 group*/
(Null,7,'N','N'),/*Writing Core Course; 1 group*/
(Null,8,'N','N'),/*Upper-Division Math Elective; 1 group*/
(Null,10,'N','N'),/*BIS Track Requirements; 1 group*/
(Null,11,'N','N'),/*CSC Track Requirements 1; 1 groups*/
(Null,12,'N','N'),/*CSC Track Requirements 2; 1 groups*/
(Null,13,'N','N'),/*CN Track Requirements; 1 group*/
(Null,14,'N','N'),/*CSE Track Requirements; 1 group*/
(Null,15,'N','N'),/*DI Track Requirements 1; 1 group*/
(Null,16,'N','N'),/*DI Track Requirements 2; 1 group*/
(Null,17,'N','N'),/*FUN Track Requirements; 1 group*/
(Null,18,'N','N'),/*SD Track Requirements; 1 group*/
(Null,9,'N','N'),/*BIS Upper-Division CIS Elective; 1 group*/
(Null,19,'N','N'),/*CSC Upper-Division Math Elective; 1 group*/
(Null,20,'N','N'),/*CN Upper-Division Math Elective; 1 group*/
(Null,21,'N','N'),/*CSE Upper-Division Math Elective; 1 group*/
(Null,22,'N','N'),/*DI Upper-Division Math Elective; 1 group*/
(Null,23,'N','N');/*SD Upper-Division Math Elective; 1 group*/



INSERT INTO `ClassesOfGroup` VALUES 
(1,28,'N'),
(1,29,'N'),
(1,30,'N'),
(1,97,'N'),
(1,98,'N'),
(2,31,'N'),
(2,32,'N'),
(2,33,'N'),
(2,35,'N'),
(2,74,'N'),
(2,76,'N'),
(2,78,'N'),
(3,103,'N'),
(3,104,'N'),
(4,106,'N'),
(4,107,'N'),
(5,100,'N'),
(5,101,'N'),
(6,99,'Y'),
(6,104,'Y'),
(6,108,'Y'),
(6,113,'Y'),
(6,115,'Y'),
(6,129,'Y'),
(7,142,'N'),
(7,143,'N'),
(7,144,'N'),
(8,145,'N'),
(8,146,'N'),
(8,147,'N'),
(9,3,'N'),
(9,4,'N'),
(9,5,'N'),
(10,6,'N'),
(10,7,'N'),
(10,8,'N'),
(11,1,'Y'),
(11,2,'Y'),
(11,3,'Y'),
(11,6,'Y'),
(11,148,'N'),
(11,149,'N'),
(12,1,'Y'),
(12,2,'Y'),
(12,3,'Y'),
(12,6,'Y'),
(12,148,'N'),
(12,150,'N'),
(13,151,'N'),
(13,152,'N'),
(13,153,'Y'),
(13,154,'Y'),
(13,155,'Y'),
(14,156,'N'),
(14,157,'Y'),
(14,158,'Y'),
(14,159,'Y'),
(15,160,'N'),
(15,161,'N'),
(15,162,'N'),
(16,165,'N'),
(16,166,'Y'),
(16,167,'Y'),
(17,163,'Y'),
(17,164,'Y'),
(18,111,'Y'),
(18,112,'Y'),
(18,113,'Y'),
(18,114,'Y'),
(18,115,'Y'),
(18,116,'Y'),
(18,117,'Y'),
(18,118,'Y'),
(18,119,'Y'),
(18,120,'Y'),
(18,121,'Y'),
(18,122,'Y'),
(18,123,'Y'),
(18,124,'Y'),
(18,125,'Y'),
(18,126,'Y'),
(18,127,'Y'),
(18,128,'Y'),
(18,129,'Y'),
(18,130,'Y'),
(18,131,'Y'),
(18,132,'Y'),
(18,133,'Y'),
(18,134,'Y'),
(18,135,'Y'),
(18,136,'Y'),
(18,137,'Y'),
(18,138,'Y'),
(18,139,'Y'),
(18,140,'Y'),
(18,141,'Y'),
(19,68,'Y'),
(19,81,'Y'),
(19,82,'Y'),
(19,84,'Y'),
(19,85,'Y'),
(19,86,'Y'),
(19,87,'Y'),
(19,94,'Y'),
(19,39,'Y'),
(20,89,'Y'),
(20,90,'Y'),
(21,73,'Y'),
(21,84,'Y'),
(21,85,'Y'),
(21,86,'Y'),
(21,87,'Y'),
(21,88,'Y'),
(21,92,'Y'),
(22,81,'N'),
(22,68,'Y'),
(22,73,'Y'),
(22,80,'Y'),
(22,82,'Y'),
(22,85,'Y'),
(22,39,'Y'),
(23,82,'N'),
(23,81,'Y'),
(23,85,'Y'),
(23,93,'Y'),
(23,94,'Y'),
(24,86,'N'),
(24,87,'Y'),
(24,88,'Y'),
(25,68,'Y'),
(25,79,'Y'),
(25,81,'Y'),
(25,84,'Y'),
(25,85,'Y'),
(25,89,'Y'),
(25,92,'Y'),
(25,93,'Y'),
(25,94,'Y'),
(25,39,'Y'),
(27,77,'N'),
(27,73,'N'),
(27,75,'N'),
(27,79,'N'),
(27,90,'N'),
(27,91,'N');

/*FUN Track Requirements; 1 group*/
INSERT INTO `ClassesOfGroup` (select 26,CID, 'Y' from Class 
where (CName like "CIS 39%" or CName like "CIS 4%" ) 
and CID not in (
select CID from TrackClasses where MID=6 and (CName like "CIS 39%" or CName like "CIS 4%" )));

/*BIS Upper-Division CIS Elective; 1 group*/
INSERT INTO `ClassesOfGroup` (select 28,CID, 'Y' from Class 
where (CName like "CIS 39%" or CName like "CIS 4%" ) 
and CID not in (
select CID from TrackClasses where MID=1 and (CName like "CIS 39%" or CName like "CIS 4%" )));
/*CSC Upper-Division Math Elective; 1 group*/
INSERT INTO `ClassesOfGroup` (select 29,CID, 'Y' from Class 
where (CName like "CIS 39%" or CName like "CIS 4%" ) 
and CID not in (
select CID from TrackClasses where MID=2 and (CName like "CIS 39%" or CName like "CIS 4%" )));
/*CN Upper-Division Math Elective; 1 group*/
INSERT INTO `ClassesOfGroup` (select 30,CID, 'Y' from Class 
where (CName like "CIS 39%" or CName like "CIS 4%" ) 
and CID not in (
select CID from TrackClasses where MID=3 and (CName like "CIS 39%" or CName like "CIS 4%" )));
/*CSE Upper-Division Math Elective; 1 group*/
INSERT INTO `ClassesOfGroup` (select 31,CID, 'Y' from Class 
where (CName like "CIS 39%" or CName like "CIS 4%" ) 
and CID not in (
select CID from TrackClasses where MID=4 and (CName like "CIS 39%" or CName like "CIS 4%" )));
/*DI Upper-Division Math Elective; 1 group*/
INSERT INTO `ClassesOfGroup` (select 32,CID, 'Y' from Class 
where (CName like "CIS 39%" or CName like "CIS 4%" ) 
and CID not in (
select CID from TrackClasses where MID=5 and (CName like "CIS 39%" or CName like "CIS 4%" )));
/*SD Upper-Division Math Elective; 1 group*/
INSERT INTO `ClassesOfGroup` (select 33,CID, 'Y' from Class 
where (CName like "CIS 39%" or CName like "CIS 4%" ) 
and CID not in (
select CID from TrackClasses where MID=7 and (CName like "CIS 39%" or CName like "CIS 4%" )));






INSERT INTO `Term` VALUES
(Null,'Fall 2013'),
(Null,'Winter 2014'),
(Null,'Spring 2014'),
(Null,'Summer 2014'),
(Null,'Fall 2014');


INSERT INTO `ScheduleClass` VALUES
(3,11),
(3,12),
(3,15),
(3,17),
(3,19),
(3,29),
(3,30),
(3,33),
(3,35),
(3,40),
(3,41),
(3,42),
(3,43),
(3,44),
(3,45),
(3,51),
(3,46),
(3,57),
(3,67),
(3,66),
(3,68),
(3,69),
(3,74),
(3,76),
(3,77),
(3,78),
(3,85),
(3,88),
(3,94),
(3,2),
(3,5),
(3,8),
(3,95),
(3,96),
(3,97),
(3,98),
(3,99),
(3,101),
(3,102),
(3,103),
(3,104),
(3,105),
(3,108),
(3,110),
(3,111),
(3,112),
(3,114),
(3,115),
(3,116),
(3,120),
(3,122),
(3,125),
(3,128),
(3,129),
(3,132),
(3,133),
(3,138),
(3,144),
(3,149),
(3,150),
(3,151),
(3,152),
(3,153),
(3,154),
(3,156),
(3,157),
(3,162),
(3,163),
(3,164);

